stages:
  - lint
  - release

include:
  - component: $CI_SERVER_HOST/buildtools/gitlab-tools/lint-helm@main
  - component: $CI_SERVER_HOST/buildtools/gitlab-tools/release-helm-oci@main
  - component: $CI_SERVER_HOST/buildtools/gitlab-tools/release-helm-oci-gitlabcom@main
  - component: $CI_SERVER_HOST/buildtools/gitlab-tools/tag-release@main
    inputs:
      version-cmd: yq e .version Chart.yaml
