stages:
  - lint
  - create-tag
  - publish

before_script:
  # start: fix gitlab-ci's umask 0000 issue
  - umask 0022
  - find . ! -path . ! -path './.git' ! -path './.git/*' -exec chmod go-w {} +
  # end: fix gitlab-ci's umask 0000 issue

helmlint:
  stage: lint
  image: $CI_REGISTRY/buildtools/kube-tools:latest
  script:
    - helm lint .

kubeconform:
  stage: lint
  image: $CI_REGISTRY/buildtools/kube-tools:latest
  script:
    - |
      helm template --namespace test --generate-name \
        --values ./test/values.yaml \
        . \
        | kubeconform --summary --strict --ignore-missing-schemas

publish:
  stage: publish
  image: $CI_REGISTRY/buildtools/kube-tools:latest
  script:
    - helm-release .
  only:
    - tags

publish:gitlabcom:
  stage: publish
  image: $CI_REGISTRY/buildtools/kube-tools:latest
  script:
    - '[[ -z "${GITLAB_COM_HELM_REGISTRY_IMAGE:-}" ]] && exit 0'
    - '[[ -z "${GITLAB_COM_USERNAME:-}" ]] && exit 0'
    - '[[ -z "${GITLAB_COM_PASSWORD:-}" ]] && exit 0'
    - echo "${GITLAB_COM_PASSWORD}" | helm registry login -u "${GITLAB_COM_USERNAME}" --password-stdin registry.gitlab.com
    - mkdir -p _helmws
    - helm package --destination=_helmws .
    - cd _helmws
    - helm push ./*.tgz "oci://${GITLAB_COM_HELM_REGISTRY_IMAGE}"
  only:
    - tags

create-tag:
  stage: create-tag
  image: $CI_REGISTRY/buildtools/gitlab-tools:latest
  script:
    - create-tag-from-head --tag "v$(grep '^version:' Chart.yaml | awk '{print $2}')"
  only:
    - master
